UPDATE "HonorRule"
SET
  "name" = '俱乐部国际一级杯赛',
  "targetType" = 'CLUB',
  "category" = '国际',
  "level" = '一级',
  "format" = '杯赛',
  "scopeType" = 'GLOBAL',
  "baseScore" = 16,
  "championScore" = 16,
  "runnerUpScore" = 8,
  "thirdPlaceScore" = 4.8,
  "fourthPlaceScore" = 3.2,
  "semiFinalistScore" = 4,
  "coefficient" = 1,
  "qualityCoefficient" = 1,
  "placementScope" = 'TOP_FOUR',
  "conversionType" = 'CLUB_WORLD_CUP_STAGE',
  "sortOrder" = 110,
  "remark" = '世俱杯等俱乐部国际一级杯赛；2025 前按阶段换算为 8 分，2025 起为 16 分。',
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "code" = 'CLUB_INTERNATIONAL_LEVEL_1_CUP'
  AND "isSystem" = true;

UPDATE "HonorRule"
SET
  "name" = '俱乐部国际二级杯赛',
  "targetType" = 'CLUB',
  "category" = '国际',
  "level" = '二级',
  "format" = '杯赛',
  "scopeType" = 'GLOBAL',
  "baseScore" = 6,
  "championScore" = 6,
  "runnerUpScore" = 3,
  "thirdPlaceScore" = NULL,
  "fourthPlaceScore" = NULL,
  "semiFinalistScore" = NULL,
  "coefficient" = 1,
  "qualityCoefficient" = 1,
  "placementScope" = 'TOP_TWO',
  "conversionType" = 'NONE',
  "sortOrder" = 120,
  "remark" = '国际足联洲际杯等各足联冠军参与的俱乐部国际二级赛事。',
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "code" = 'CLUB_INTERNATIONAL_LEVEL_2_CUP'
  AND "isSystem" = true;

INSERT INTO "HonorRule" (
  "id",
  "code",
  "name",
  "targetType",
  "category",
  "level",
  "format",
  "scopeType",
  "baseScore",
  "championScore",
  "runnerUpScore",
  "thirdPlaceScore",
  "fourthPlaceScore",
  "semiFinalistScore",
  "coefficient",
  "qualityCoefficient",
  "placementScope",
  "conversionType",
  "isSystem",
  "enabled",
  "sortOrder",
  "remark",
  "createdAt",
  "updatedAt"
)
VALUES (
  'system_club_international_level_3_cup',
  'CLUB_INTERNATIONAL_LEVEL_3_CUP',
  '俱乐部国际三级杯赛',
  'CLUB',
  '国际',
  '三级',
  '杯赛',
  'GLOBAL',
  4,
  4,
  2,
  NULL,
  NULL,
  NULL,
  1,
  1,
  'TOP_TWO',
  'NONE',
  true,
  true,
  130,
  '丰田杯、旧洲际杯等欧冠冠军与南美冠军之间的单场世界冠军杯。',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("code") DO UPDATE
SET
  "name" = EXCLUDED."name",
  "targetType" = EXCLUDED."targetType",
  "category" = EXCLUDED."category",
  "level" = EXCLUDED."level",
  "format" = EXCLUDED."format",
  "scopeType" = EXCLUDED."scopeType",
  "baseScore" = EXCLUDED."baseScore",
  "championScore" = EXCLUDED."championScore",
  "runnerUpScore" = EXCLUDED."runnerUpScore",
  "thirdPlaceScore" = EXCLUDED."thirdPlaceScore",
  "fourthPlaceScore" = EXCLUDED."fourthPlaceScore",
  "semiFinalistScore" = EXCLUDED."semiFinalistScore",
  "coefficient" = EXCLUDED."coefficient",
  "qualityCoefficient" = EXCLUDED."qualityCoefficient",
  "placementScope" = EXCLUDED."placementScope",
  "conversionType" = EXCLUDED."conversionType",
  "isSystem" = EXCLUDED."isSystem",
  "enabled" = EXCLUDED."enabled",
  "sortOrder" = EXCLUDED."sortOrder",
  "remark" = EXCLUDED."remark",
  "updatedAt" = CURRENT_TIMESTAMP;
