UPDATE "Competition"
SET "sortOrder" = CASE "code"
  WHEN 'FIFA_WORLD_CUP' THEN 0
  WHEN 'FIFA_CONFEDERATIONS_CUP' THEN 1
  WHEN 'OLYMPIC_MENS_FOOTBALL' THEN 2
  WHEN 'AFRICA_CUP' THEN 10
  WHEN 'AFC_ASIAN_CUP' THEN 20
  WHEN 'UEFA_EURO' THEN 30
  WHEN 'CONCACAF_GOLD_CUP' THEN 40
  WHEN 'OFC_NATIONS_CUP' THEN 50
  WHEN 'COPA_AMERICA' THEN 60
  WHEN 'FIFA_CLUB_WORLD_CUP' THEN 0
  WHEN 'FIFA_INTERCONTINENTAL_CUP' THEN 1
  WHEN 'EUROPEAN_SOUTH_AMERICAN_CUP' THEN 2
  WHEN 'UEFA_CHAMPIONS_LEAGUE' THEN 30
  ELSE "sortOrder"
END
WHERE "code" IN (
  'FIFA_WORLD_CUP',
  'FIFA_CONFEDERATIONS_CUP',
  'OLYMPIC_MENS_FOOTBALL',
  'AFRICA_CUP',
  'AFC_ASIAN_CUP',
  'UEFA_EURO',
  'CONCACAF_GOLD_CUP',
  'OFC_NATIONS_CUP',
  'COPA_AMERICA',
  'FIFA_CLUB_WORLD_CUP',
  'FIFA_INTERCONTINENTAL_CUP',
  'EUROPEAN_SOUTH_AMERICAN_CUP',
  'UEFA_CHAMPIONS_LEAGUE'
);
