UPDATE "HonorRule"
SET "format" = '杯赛'
WHERE "code" IN (
  'COUNTRY_INTERNATIONAL_LEVEL_1_OTHER',
  'COUNTRY_INTERNATIONAL_LEVEL_2_OTHER',
  'COUNTRY_INTERNATIONAL_LEVEL_3_OTHER'
);

DELETE FROM "HonorRule"
WHERE "code" = 'CLUB_INTERNATIONAL_LEVEL_2_OTHER'
  AND "isSystem" = true;
